### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by negru555** [stellitecoin/xtl-stak#1]
I use Window 8.
It disables backend Nvidia when I start xtl-stak backend Nvidia. The nvidia.txt config is empty.
If I use the nividia.txt from xmr-stak(xmr-stak works perfectly) it tells me 
[2018-06-10 10:15:14] : Mining coin: stellite
[2018-06-10 10:15:14] : Starting NVIDIA GPU thread 0, no affinity.
WARNING: NVIDIA GPU 0: miner not compiled for CUDA architecture 21.
[2018-06-10 10:15:14] : Setup failed for GPU 0. Exiting.
My gpu is Nvdia Geforce 710M. 
The CPU works perfectly
CPU - i5-3230M 4 cores @ 2.6 Ghz

**Comment by donovansolms** [comment]
Hi,
We've identified the issue, the bundled CUDA libraries don't support older card models. We'll be releasing an update soon with the fix.
